"""Build supabase/seed.sql from src/data/catalog.json (the same content the app shows today).

IDs are deterministic (uuid5), so re-running produces identical SQL and tests can refer to rows.
Usage: python3 scripts/build_seed.py
"""
import json
import uuid
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
CAT = json.loads((ROOT / "src/data/catalog.json").read_text(encoding="utf-8"))
NS = uuid.UUID("5ea3f0a0-7e6b-4c1e-9b1a-000000000000")
SLOT_ORDER = ["outer", "top", "bottom", "shoes", "bag"]


def uid(kind, key):
    return str(uuid.uuid5(NS, f"{kind}:{key}"))


def q(v):
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"


def arr(values):
    return "array[" + ",".join(q(v) for v in values) + "]::text[]" if values else "'{}'::text[]"


def main():
    out = ["-- Generated by scripts/build_seed.py from src/data/catalog.json. Do not edit by hand.",
           "-- Demo content in USD. Price-band thresholds for EGP and SAR are placeholders pending commercial sign-off.",
           "",
           "insert into public.markets (code, name, default_currency, default_locale, active) values",
           "  ('EG', 'Egypt', 'EGP', 'ar', true),",
           "  ('SA', 'Saudi Arabia', 'SAR', 'ar', true);",
           "",
           "insert into public.price_bands (currency, t1, t2, t3) values",
           "  ('USD', 5000, 15000, 40000),        -- $50 / $150 / $400",
           "  ('EGP', 250000, 750000, 2000000),   -- EGP 2,500 / 7,500 / 20,000 (placeholder)",
           "  ('SAR', 19000, 56000, 150000);      -- SAR 190 / 560 / 1,500 (placeholder)",
           ""]

    # Creators are real auth users so the profile trigger and foreign keys behave exactly as in production.
    for c in CAT["creators"]:
        out.append(
            "insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, "
            "raw_user_meta_data, created_at, updated_at) values ("
            f"'00000000-0000-0000-0000-000000000000', {q(uid('creator', c['id']))}, 'authenticated', 'authenticated', "
            f"{q(c['id'] + '@creators.seam.test')}, '', now(), "
            f"{q(json.dumps({'handle': c['handle'].lstrip('@'), 'display_name': c['name']}))}::jsonb, now(), now());")
        out.append(
            f"update public.profiles set is_creator = true, bio = {q(c['bio'])}, market_code = 'EG', "
            f"website = {q(c['website']) if c.get('website') else 'null'}, "
            f"avatar_path = {q(uid('creator', c['id']) + '/avatar.jpg')} where id = {q(uid('creator', c['id']))};")
    out.append("")

    retailers = sorted({p["retailer"] for p in CAT["products"]})
    out.append("insert into public.retailers (id, name, domain, markets) values")
    out.append(",\n".join(
        f"  ({q(uid('retailer', r))}, {q(r)}, {q(r.lower().replace(' ', '') + '.example.com')}, array['EG','SA']::char(2)[])"
        for r in retailers) + ";")
    brands = sorted({p["brand"] for p in CAT["products"]})
    out.append("insert into public.brands (id, name, slug) values")
    out.append(",\n".join(f"  ({q(uid('brand', b))}, {q(b)}, {q(b.lower().replace(' ', '-'))})" for b in brands) + ";")
    out.append("")

    out.append("insert into public.products (id, retailer_id, brand_id, external_id, slot, name, color_hex, "
               "price_minor, currency, stock, product_url, image_urls) values")
    rows = []
    for p in CAT["products"]:
        rows.append(
            f"  ({q(uid('product', p['id']))}, {q(uid('retailer', p['retailer']))}, {q(uid('brand', p['brand']))}, "
            f"{q(p['id'])}, {q(p['category'])}, {q(p['name'])}, {q(p['color'])}, {p['price'] * 100}, 'USD', "
            f"{q(p['stock'])}, {q('https://example.com/shop/' + p['id'])}, {arr(['products/' + p['id'] + '.jpg'])})")
    out.append(",\n".join(rows) + ";")
    out.append("")

    order = CAT["feedOrder"]
    for i, look_id in enumerate(order):
        look = next(l for l in CAT["looks"] if l["id"] == look_id)
        creator = uid("creator", look["creator"])
        w, h = Image.open(ROOT / "assets/images/looks" / f"{look_id}.jpg").size
        out.append(
            "insert into public.looks (id, creator_id, image_path, width, height, caption, style, occasion, season, "
            "link, status, market_code, published_at) values ("
            f"{q(uid('look', look_id))}, {q(creator)}, {q(creator + '/' + look_id + '.jpg')}, {w}, {h}, "
            f"{q(look['caption'])}, {q(look['style'])}, {q(look['occasion'])}, {q(look['season'])}, "
            f"{q(look['link']) if look.get('link') else 'null'}, 'published', 'EG', "
            f"now() - interval '{i} hours');")
        pieces = sorted(look["pieces"], key=lambda pc: SLOT_ORDER.index(pc["slot"]))
        vals = []
        for pos, pc in enumerate(pieces, start=1):
            # Authored per Look against its own photograph, never derived from the slot.
            x, y = pc["x"], pc["y"]
            prod = next((p for p in CAT["products"] if p["id"] == pc["product"]), None)
            slot = prod["category"] if prod else pc["slot"]
            label = prod["label"] if prod else pc.get("label", "PIECE")
            vals.append(f"  ({q(uid('look', look_id))}, {pos}, {q(slot)}, {q(label)}, {x}, {y}, "
                        f"{q(uid('product', pc['product'])) if pc['product'] else 'null'})")
        out.append("insert into public.look_pieces (look_id, position, slot, label, x, y, product_id) values")
        out.append(",\n".join(vals) + ";")
    out.append("")
    (ROOT / "supabase/seed.sql").write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"seed.sql: {len(CAT['creators'])} creators, {len(retailers)} retailers, {len(brands)} brands, "
          f"{len(CAT['products'])} products, {len(order)} looks")


if __name__ == "__main__":
    main()
